spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.data-source-properties.sslmode=${POSTGRES_SSLMODE:disable}
