spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.data-source-properties.sslmode=${POSTGRES_SSLMODE:verify-full}

spring.servlet.multipart.max-file-size=${SPRING_MULTIPART_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${SPRING_MULTIPART_MAX_REQUEST_SIZE:5MB}
